/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CatalogoRouteImport } from './routes/catalogo'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as PoliticaDeDevolucionRouteImport } from './routes/politica-de-devolucion'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminBannerRouteImport } from './routes/admin.banner'
import { Route as AdminCategoriasRouteImport } from './routes/admin.categorias'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminPreciosRouteImport } from './routes/admin.precios'
import { Route as CategoriaSlugRouteImport } from './routes/categoria.$slug'
import { Route as ElectronicaSplatRouteImport } from './routes/electronica.$'
import { Route as HerramientasSplatRouteImport } from './routes/herramientas.$'
import { Route as MediaFileRouteImport } from './routes/media.$file'
import { Route as PedidoIdRouteImport } from './routes/pedido.$id'
import { Route as ProductoSlugRouteImport } from './routes/producto.$slug'
import { Route as ProductosIndexRouteImport } from './routes/productos.index'
import { Route as ProductosSlugRouteImport } from './routes/productos.$slug'
import { Route as AdminPedidosIndexRouteImport } from './routes/admin.pedidos.index'
import { Route as AdminPedidosIdRouteImport } from './routes/admin.pedidos.$id'
import { Route as AdminProductosIndexRouteImport } from './routes/admin.productos.index'
import { Route as AdminProductosSlugRouteImport } from './routes/admin.productos.$slug'
import { Route as ApiAdminRespaldoRouteImport } from './routes/api.admin.respaldo'
import { Route as ApiMercadopagoWebhookRouteImport } from './routes/api.mercadopago.webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogoRoute = CatalogoRouteImport.update({
  id: '/catalogo',
  path: '/catalogo',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaDeDevolucionRoute = PoliticaDeDevolucionRouteImport.update({
  id: '/politica-de-devolucion',
  path: '/politica-de-devolucion',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBannerRoute = AdminBannerRouteImport.update({
  id: '/banner',
  path: '/banner',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriasRoute = AdminCategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPreciosRoute = AdminPreciosRouteImport.update({
  id: '/precios',
  path: '/precios',
  getParentRoute: () => AdminRoute,
} as any)
const CategoriaSlugRoute = CategoriaSlugRouteImport.update({
  id: '/categoria/$slug',
  path: '/categoria/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ElectronicaSplatRoute = ElectronicaSplatRouteImport.update({
  id: '/electronica/$',
  path: '/electronica/$',
  getParentRoute: () => rootRouteImport,
} as any)
const HerramientasSplatRoute = HerramientasSplatRouteImport.update({
  id: '/herramientas/$',
  path: '/herramientas/$',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaFileRoute = MediaFileRouteImport.update({
  id: '/media/$file',
  path: '/media/$file',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidoIdRoute = PedidoIdRouteImport.update({
  id: '/pedido/$id',
  path: '/pedido/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductoSlugRoute = ProductoSlugRouteImport.update({
  id: '/producto/$slug',
  path: '/producto/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductosIndexRoute = ProductosIndexRouteImport.update({
  id: '/productos/',
  path: '/productos/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductosSlugRoute = ProductosSlugRouteImport.update({
  id: '/productos/$slug',
  path: '/productos/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPedidosIndexRoute = AdminPedidosIndexRouteImport.update({
  id: '/pedidos/',
  path: '/pedidos/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPedidosIdRoute = AdminPedidosIdRouteImport.update({
  id: '/pedidos/$id',
  path: '/pedidos/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductosIndexRoute = AdminProductosIndexRouteImport.update({
  id: '/productos/',
  path: '/productos/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductosSlugRoute = AdminProductosSlugRouteImport.update({
  id: '/productos/$slug',
  path: '/productos/$slug',
  getParentRoute: () => AdminRoute,
} as any)
const ApiAdminRespaldoRoute = ApiAdminRespaldoRouteImport.update({
  id: '/api/admin/respaldo',
  path: '/api/admin/respaldo',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMercadopagoWebhookRoute = ApiMercadopagoWebhookRouteImport.update({
  id: '/api/mercadopago/webhook',
  path: '/api/mercadopago/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/catalogo': typeof CatalogoRoute
  '/checkout': typeof CheckoutRoute
  '/contacto': typeof ContactoRoute
  '/politica-de-devolucion': typeof PoliticaDeDevolucionRoute
  '/admin/banner': typeof AdminBannerRoute
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/precios': typeof AdminPreciosRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/electronica/$': typeof ElectronicaSplatRoute
  '/herramientas/$': typeof HerramientasSplatRoute
  '/media/$file': typeof MediaFileRoute
  '/pedido/$id': typeof PedidoIdRoute
  '/producto/$slug': typeof ProductoSlugRoute
  '/productos/$slug': typeof ProductosSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/productos/': typeof ProductosIndexRoute
  '/admin/pedidos/$id': typeof AdminPedidosIdRoute
  '/admin/productos/$slug': typeof AdminProductosSlugRoute
  '/api/admin/respaldo': typeof ApiAdminRespaldoRoute
  '/api/mercadopago/webhook': typeof ApiMercadopagoWebhookRoute
  '/admin/pedidos/': typeof AdminPedidosIndexRoute
  '/admin/productos/': typeof AdminProductosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/catalogo': typeof CatalogoRoute
  '/checkout': typeof CheckoutRoute
  '/contacto': typeof ContactoRoute
  '/politica-de-devolucion': typeof PoliticaDeDevolucionRoute
  '/admin/banner': typeof AdminBannerRoute
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/precios': typeof AdminPreciosRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/electronica/$': typeof ElectronicaSplatRoute
  '/herramientas/$': typeof HerramientasSplatRoute
  '/media/$file': typeof MediaFileRoute
  '/pedido/$id': typeof PedidoIdRoute
  '/producto/$slug': typeof ProductoSlugRoute
  '/productos/$slug': typeof ProductosSlugRoute
  '/admin': typeof AdminIndexRoute
  '/productos': typeof ProductosIndexRoute
  '/admin/pedidos/$id': typeof AdminPedidosIdRoute
  '/admin/productos/$slug': typeof AdminProductosSlugRoute
  '/api/admin/respaldo': typeof ApiAdminRespaldoRoute
  '/api/mercadopago/webhook': typeof ApiMercadopagoWebhookRoute
  '/admin/pedidos': typeof AdminPedidosIndexRoute
  '/admin/productos': typeof AdminProductosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/catalogo': typeof CatalogoRoute
  '/checkout': typeof CheckoutRoute
  '/contacto': typeof ContactoRoute
  '/politica-de-devolucion': typeof PoliticaDeDevolucionRoute
  '/admin/banner': typeof AdminBannerRoute
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/precios': typeof AdminPreciosRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/electronica/$': typeof ElectronicaSplatRoute
  '/herramientas/$': typeof HerramientasSplatRoute
  '/media/$file': typeof MediaFileRoute
  '/pedido/$id': typeof PedidoIdRoute
  '/producto/$slug': typeof ProductoSlugRoute
  '/productos/$slug': typeof ProductosSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/productos/': typeof ProductosIndexRoute
  '/admin/pedidos/$id': typeof AdminPedidosIdRoute
  '/admin/productos/$slug': typeof AdminProductosSlugRoute
  '/api/admin/respaldo': typeof ApiAdminRespaldoRoute
  '/api/mercadopago/webhook': typeof ApiMercadopagoWebhookRoute
  '/admin/pedidos/': typeof AdminPedidosIndexRoute
  '/admin/productos/': typeof AdminProductosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/catalogo'
    | '/checkout'
    | '/contacto'
    | '/politica-de-devolucion'
    | '/admin/banner'
    | '/admin/categorias'
    | '/admin/login'
    | '/admin/precios'
    | '/categoria/$slug'
    | '/electronica/$'
    | '/herramientas/$'
    | '/media/$file'
    | '/pedido/$id'
    | '/producto/$slug'
    | '/productos/$slug'
    | '/admin/'
    | '/productos/'
    | '/admin/pedidos/$id'
    | '/admin/productos/$slug'
    | '/api/admin/respaldo'
    | '/api/mercadopago/webhook'
    | '/admin/pedidos/'
    | '/admin/productos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/catalogo'
    | '/checkout'
    | '/contacto'
    | '/politica-de-devolucion'
    | '/admin/banner'
    | '/admin/categorias'
    | '/admin/login'
    | '/admin/precios'
    | '/categoria/$slug'
    | '/electronica/$'
    | '/herramientas/$'
    | '/media/$file'
    | '/pedido/$id'
    | '/producto/$slug'
    | '/productos/$slug'
    | '/admin'
    | '/productos'
    | '/admin/pedidos/$id'
    | '/admin/productos/$slug'
    | '/api/admin/respaldo'
    | '/api/mercadopago/webhook'
    | '/admin/pedidos'
    | '/admin/productos'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/catalogo'
    | '/checkout'
    | '/contacto'
    | '/politica-de-devolucion'
    | '/admin/banner'
    | '/admin/categorias'
    | '/admin/login'
    | '/admin/precios'
    | '/categoria/$slug'
    | '/electronica/$'
    | '/herramientas/$'
    | '/media/$file'
    | '/pedido/$id'
    | '/producto/$slug'
    | '/productos/$slug'
    | '/admin/'
    | '/productos/'
    | '/admin/pedidos/$id'
    | '/admin/productos/$slug'
    | '/api/admin/respaldo'
    | '/api/mercadopago/webhook'
    | '/admin/pedidos/'
    | '/admin/productos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CatalogoRoute: typeof CatalogoRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactoRoute: typeof ContactoRoute
  PoliticaDeDevolucionRoute: typeof PoliticaDeDevolucionRoute
  CategoriaSlugRoute: typeof CategoriaSlugRoute
  ElectronicaSplatRoute: typeof ElectronicaSplatRoute
  HerramientasSplatRoute: typeof HerramientasSplatRoute
  MediaFileRoute: typeof MediaFileRoute
  PedidoIdRoute: typeof PedidoIdRoute
  ProductoSlugRoute: typeof ProductoSlugRoute
  ProductosSlugRoute: typeof ProductosSlugRoute
  ProductosIndexRoute: typeof ProductosIndexRoute
  ApiAdminRespaldoRoute: typeof ApiAdminRespaldoRoute
  ApiMercadopagoWebhookRoute: typeof ApiMercadopagoWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogo': {
      id: '/catalogo'
      path: '/catalogo'
      fullPath: '/catalogo'
      preLoaderRoute: typeof CatalogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-devolucion': {
      id: '/politica-de-devolucion'
      path: '/politica-de-devolucion'
      fullPath: '/politica-de-devolucion'
      preLoaderRoute: typeof PoliticaDeDevolucionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/banner': {
      id: '/admin/banner'
      path: '/banner'
      fullPath: '/admin/banner'
      preLoaderRoute: typeof AdminBannerRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categorias': {
      id: '/admin/categorias'
      path: '/categorias'
      fullPath: '/admin/categorias'
      preLoaderRoute: typeof AdminCategoriasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/precios': {
      id: '/admin/precios'
      path: '/precios'
      fullPath: '/admin/precios'
      preLoaderRoute: typeof AdminPreciosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/categoria/$slug': {
      id: '/categoria/$slug'
      path: '/categoria/$slug'
      fullPath: '/categoria/$slug'
      preLoaderRoute: typeof CategoriaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/electronica/$': {
      id: '/electronica/$'
      path: '/electronica/$'
      fullPath: '/electronica/$'
      preLoaderRoute: typeof ElectronicaSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/herramientas/$': {
      id: '/herramientas/$'
      path: '/herramientas/$'
      fullPath: '/herramientas/$'
      preLoaderRoute: typeof HerramientasSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media/$file': {
      id: '/media/$file'
      path: '/media/$file'
      fullPath: '/media/$file'
      preLoaderRoute: typeof MediaFileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedido/$id': {
      id: '/pedido/$id'
      path: '/pedido/$id'
      fullPath: '/pedido/$id'
      preLoaderRoute: typeof PedidoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/producto/$slug': {
      id: '/producto/$slug'
      path: '/producto/$slug'
      fullPath: '/producto/$slug'
      preLoaderRoute: typeof ProductoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/productos/': {
      id: '/productos/'
      path: '/productos'
      fullPath: '/productos/'
      preLoaderRoute: typeof ProductosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/productos/$slug': {
      id: '/productos/$slug'
      path: '/productos/$slug'
      fullPath: '/productos/$slug'
      preLoaderRoute: typeof ProductosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/pedidos/': {
      id: '/admin/pedidos/'
      path: '/pedidos'
      fullPath: '/admin/pedidos/'
      preLoaderRoute: typeof AdminPedidosIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pedidos/$id': {
      id: '/admin/pedidos/$id'
      path: '/pedidos/$id'
      fullPath: '/admin/pedidos/$id'
      preLoaderRoute: typeof AdminPedidosIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/productos/': {
      id: '/admin/productos/'
      path: '/productos'
      fullPath: '/admin/productos/'
      preLoaderRoute: typeof AdminProductosIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/productos/$slug': {
      id: '/admin/productos/$slug'
      path: '/productos/$slug'
      fullPath: '/admin/productos/$slug'
      preLoaderRoute: typeof AdminProductosSlugRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/admin/respaldo': {
      id: '/api/admin/respaldo'
      path: '/api/admin/respaldo'
      fullPath: '/api/admin/respaldo'
      preLoaderRoute: typeof ApiAdminRespaldoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mercadopago/webhook': {
      id: '/api/mercadopago/webhook'
      path: '/api/mercadopago/webhook'
      fullPath: '/api/mercadopago/webhook'
      preLoaderRoute: typeof ApiMercadopagoWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminBannerRoute: typeof AdminBannerRoute
  AdminCategoriasRoute: typeof AdminCategoriasRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminPreciosRoute: typeof AdminPreciosRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminPedidosIdRoute: typeof AdminPedidosIdRoute
  AdminProductosSlugRoute: typeof AdminProductosSlugRoute
  AdminPedidosIndexRoute: typeof AdminPedidosIndexRoute
  AdminProductosIndexRoute: typeof AdminProductosIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBannerRoute: AdminBannerRoute,
  AdminCategoriasRoute: AdminCategoriasRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminPreciosRoute: AdminPreciosRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminPedidosIdRoute: AdminPedidosIdRoute,
  AdminProductosSlugRoute: AdminProductosSlugRoute,
  AdminPedidosIndexRoute: AdminPedidosIndexRoute,
  AdminProductosIndexRoute: AdminProductosIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CatalogoRoute: CatalogoRoute,
  CheckoutRoute: CheckoutRoute,
  ContactoRoute: ContactoRoute,
  PoliticaDeDevolucionRoute: PoliticaDeDevolucionRoute,
  CategoriaSlugRoute: CategoriaSlugRoute,
  ElectronicaSplatRoute: ElectronicaSplatRoute,
  HerramientasSplatRoute: HerramientasSplatRoute,
  MediaFileRoute: MediaFileRoute,
  PedidoIdRoute: PedidoIdRoute,
  ProductoSlugRoute: ProductoSlugRoute,
  ProductosSlugRoute: ProductosSlugRoute,
  ProductosIndexRoute: ProductosIndexRoute,
  ApiAdminRespaldoRoute: ApiAdminRespaldoRoute,
  ApiMercadopagoWebhookRoute: ApiMercadopagoWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
